apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-engine-backend
spec:
  replicas: 3 # Start with 3 replicas
  selector:
    matchLabels:
      app: betting-engine
  template:
    metadata:
      labels:
        app: betting-engine
    spec:
      containers:
        - name: backend
          # Replace with your actual image path in a container registry
          image: real-time-betting-engine:latest
          imagePullPolicy: Never # necessary for local images
          ports:
            - containerPort: 8081
          env:
            - name: NATS_URL
              value: "nats://host.docker.internal:4222" # Assuming a NATS service named 'nats-service'
            - name: COCKROACHDB_URL
              value: "postgresql://root@cockroachdb:26257/defaultdb?sslmode=disable"
            - name: REDIS_URL
              value: "redis-service:6379"
            - name: POSTGRES_URL
              value: "postgresql://postgres:example@postgres-service:5432/postgres?sslmode=disable"
