apiVersion: v1
kind: Service
metadata:
  name: betting-engine-service
spec:
  selector:
    app: betting-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # Exposes the service outside the cluster
