apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-lb
spec:
  type: LoadBalancer
  selector:
    app: cockroachdb
  ports:
    - port: 26257
      targetPort: 26257
      name: sql
    - port: 8080
      targetPort: 8080
      name: http
