# A simplified CockroachDB StatefulSet for demonstration.
# For production, use the official CockroachDB Kubernetes Operator.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  serviceName: "cockroachdb"
  replicas: 3
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:latest-v23.2
          args:
            - "start"
            - "--insecure"
            - "--join=cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb"
            - "--listen-addr=0.0.0.0"
          ports:
            - containerPort: 26257
              name: grpc
            - containerPort: 8080
              name: http
