apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: betting-engine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: betting-engine-backend
  minReplicas: 1
  maxReplicas: 20 # Scale up to 20 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 # Scale up when CPU usage hits 80%
