apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: betting-engine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: betting-engine-backend
  minReplicas: 3
  maxReplicas: 20 # Scale up to 20 pods
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 25Mi
